"""Build stage.

Ports the "build" mode of the trusted ``reference_build_clips.py`` production
script: it resolves the Curator's block-index selections against the corrected
SRT and copies the EXACT timestamps and VERBATIM transcript text from the SRT.
No field here is generated by AI — the curator only points at block indexes; the
deterministic logic below does the rest.

On top of the port it computes ``beep_timestamps`` per clip (bleep ranges that
intersect the clip's window, re-based to clip-relative seconds), assembles the
manifest, writes it to the workspace + S3 AND the PipelineJob row, and pauses
the job at the human gate (status AWAITING_MANIFEST_APPROVAL). This is the last
stage for now.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import date
from typing import TYPE_CHECKING, Any

from worker import jobs

if TYPE_CHECKING:
    from worker.stages import StageContext

logger = logging.getLogger(__name__)

TIME_RE = re.compile(r"(\d{2}):(\d{2}):(\d{2})[,.](\d{3})")

# Advisory duration window (ported from the reference: outside this range a clip
# is kept but flagged for review).
MIN_REVIEW_SECONDS = 20.0
MAX_REVIEW_SECONDS = 160.0


class BuildError(RuntimeError):
    """Raised when the build stage cannot produce a manifest at all."""


class InvalidClip(Exception):
    """A clip whose block range can't be resolved against the SRT (skip it)."""


def run_build(ctx: StageContext) -> None:
    """Assemble the manifest and pause the job at the approval gate."""

    ws = ctx.workspace
    job = ctx.job
    state = ws.read_state()

    srt_key = _require_key(state, "ingest", "corrected_srt_key")
    bleep_key = _require_key(state, "ingest", "bleep_ranges_key")
    bleeped_key = _require_key(state, "ingest", "bleeped_video_key")
    mindset_key = _require_key(state, "curate", "mindset")
    technical_key = _require_key(state, "curate", "technical")

    srt_text = ws.download(srt_key, "build_input.srt").read_text(
        encoding="utf-8-sig", errors="replace"
    )
    bleep_ranges = _load_bleep_ranges(ws.download(bleep_key, "build_bleeps.json"))
    curations = [
        json.loads(ws.download(mindset_key, "build_mindset.json").read_text()),
        json.loads(ws.download(technical_key, "build_technical.json").read_text()),
    ]

    manifest = build_manifest(
        srt_text=srt_text,
        curations=curations,
        bleep_ranges=bleep_ranges,
        source_video=bleeped_key,
        srt_file=srt_key,
    )
    logger.info(
        "build[%s]: %d clip(s), %d rejected segment(s)",
        job.id,
        len(manifest["clips"]),
        len(manifest["rejected_segments"]),
    )

    out = ws.path("manifest.json")
    out.write_text(json.dumps(manifest, ensure_ascii=False, indent=2))
    manifest_key = f"pipeline/{job.id}/manifest.json"
    ws.upload(out, manifest_key)

    jobs.save_manifest_awaiting_approval(ctx.conn, job.id, manifest)

    state = ws.read_state()
    state["build"] = {"manifest_key": manifest_key}
    ws.write_state(state)
    logger.info("build[%s]: manifest stored; awaiting manifest approval", job.id)


# --------------------------------------------------------------------------- #
# Pure helpers (unit-tested; no S3/DB side effects)
# --------------------------------------------------------------------------- #


def ts_to_seconds(ts: str) -> float:
    """Parse an SRT timestamp (00:01:57,320 or 00:01:57.320) to seconds."""

    match = TIME_RE.match(ts.strip())
    if match is None:
        raise ValueError(f"bad timestamp: {ts!r}")
    hours = int(match.group(1))
    minutes = int(match.group(2))
    seconds = int(match.group(3))
    millis = int(match.group(4))
    return hours * 3600 + minutes * 60 + seconds + millis / 1000.0


def parse_srt(text: str) -> dict[int, dict[str, str]]:
    """Return {index: {start, end, text}} keyed by the SRT's own block indexes."""

    blocks: dict[int, dict[str, str]] = {}
    for chunk in re.split(r"\n\s*\n", text.strip()):
        lines = [line for line in chunk.splitlines() if line.strip() != ""]
        if len(lines) < 2:
            continue
        try:
            idx = int(lines[0].strip())
        except ValueError:
            continue
        timing = re.match(r"\s*(\S+)\s*-->\s*(\S+)", lines[1])
        if timing is None:
            continue
        blocks[idx] = {
            "start": timing.group(1),
            "end": timing.group(2),
            "text": "\n".join(lines[2:]),
        }
    return blocks


def resolve_blocks(
    blocks: dict[int, dict[str, str]], start_block: Any, end_block: Any
) -> tuple[str, str, str]:
    """Resolve a block range to (start_ts, end_ts, verbatim_transcript).

    Raises :class:`InvalidClip` if the range is malformed or references any
    block index that doesn't exist in the SRT (the anti-hallucination gate:
    every block in [start, end] must exist, matching the reference script).
    """

    if not _is_int(start_block) or not _is_int(end_block) or start_block > end_block:
        raise InvalidClip(f"invalid block range {start_block}-{end_block}")
    missing = [i for i in range(start_block, end_block + 1) if i not in blocks]
    if missing:
        raise InvalidClip(f"blocks {missing} do not exist in SRT")

    start = blocks[start_block]["start"]
    end = blocks[end_block]["end"]
    transcript = "\n".join(blocks[i]["text"] for i in range(start_block, end_block + 1))
    return start, end, transcript


def intersect_beeps(
    bleep_ranges: list[list[float]], clip_start: float, clip_end: float
) -> list[list[float]]:
    """Return bleep ranges overlapping [clip_start, clip_end], clip-relative.

    Each returned pair is ``[start, end]`` in seconds from the clip's start.
    Ranges that only touch a boundary (zero overlap) or are disjoint are omitted.
    """

    beeps: list[list[float]] = []
    for pair in bleep_ranges:
        beep_start = float(pair[0])
        beep_end = float(pair[1])
        overlap_start = max(beep_start, clip_start)
        overlap_end = min(beep_end, clip_end)
        if overlap_end > overlap_start:
            beeps.append(
                [
                    round(overlap_start - clip_start, 3),
                    round(overlap_end - clip_start, 3),
                ]
            )
    return beeps


def build_manifest(
    *,
    srt_text: str,
    curations: list[dict[str, Any]],
    bleep_ranges: list[list[float]],
    source_video: str,
    srt_file: str,
    generated: str | None = None,
) -> dict[str, Any]:
    """Assemble the review manifest from the SRT + curation files + bleep ranges."""

    blocks = parse_srt(srt_text)
    if not blocks:
        raise BuildError("no subtitle blocks found in SRT")

    clips: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    counter = 0

    for data in curations:
        category = data.get("category", "uncategorized")
        for clip in data.get("selected_clips", []):
            counter += 1
            cid = f"clip_{counter:02d}"
            start_block = clip.get("start_block")
            end_block = clip.get("end_block")
            try:
                start, end, transcript = resolve_blocks(blocks, start_block, end_block)
            except InvalidClip as exc:
                logger.warning("build: %s %s — SKIPPED", cid, exc)
                continue

            start_sec = ts_to_seconds(start)
            end_sec = ts_to_seconds(end)
            duration = round(end_sec - start_sec, 1)
            if duration <= 0:
                logger.warning("build: %s non-positive duration — SKIPPED", cid)
                continue
            if duration < MIN_REVIEW_SECONDS or duration > MAX_REVIEW_SECONDS:
                logger.warning(
                    "build: %s duration %.1fs outside %g-%gs — kept, REVIEW",
                    cid,
                    duration,
                    MIN_REVIEW_SECONDS,
                    MAX_REVIEW_SECONDS,
                )

            clips.append(
                {
                    "id": cid,
                    "approved": None,
                    "category": category,
                    "confidence": clip.get("confidence", "high"),
                    "start_block": start_block,
                    "end_block": end_block,
                    "start": start,
                    "end": end,
                    "duration_seconds": duration,
                    "title": clip.get("title", ""),
                    "summary": clip.get("summary", ""),
                    "rationale": clip.get("rationale", ""),
                    "transcript": transcript,
                    "hook_prompt": None,
                    "close_prompt": None,
                    "post_copy": None,
                    "beep_timestamps": intersect_beeps(bleep_ranges, start_sec, end_sec),
                }
            )

        for rej in data.get("rejected_segments", []):
            entry = dict(rej)
            entry["category"] = category
            rejected.append(entry)

    return {
        "source_video": source_video,
        "srt_file": srt_file,
        "generated": generated if generated is not None else str(date.today()),
        "status": "pending_approval",
        "clips": clips,
        "rejected_segments": rejected,
    }


def _is_int(value: Any) -> bool:
    # bool is a subclass of int; exclude it so True/False aren't valid indexes.
    return isinstance(value, int) and not isinstance(value, bool)


def _load_bleep_ranges(path: Any) -> list[list[float]]:
    parsed: Any = json.loads(path.read_text())
    if not isinstance(parsed, list):
        return []
    return [[float(pair[0]), float(pair[1])] for pair in parsed]


def _require_key(state: dict[str, Any], stage: str, field: str) -> str:
    section = state.get(stage, {})
    value = section.get(field) if isinstance(section, dict) else None
    if not isinstance(value, str) or not value:
        raise BuildError(
            f"build: missing {stage}.{field} in workspace state "
            "(earlier stages must run first)"
        )
    return value
